LTE/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /LTE/
    url(r'^$', views.index, name='index'),
]

SpamAlyzer/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^conversation/spam/web/(?P<num_page>[0-9]+)', views.conversation, name="conversation"),
    url(r'^historique/depot', views.historique, name="histoDepot"),
    url(r'^stats/globales', views.statsGlobales, name="statsGlobales"),
    url(r'^stats/spammeurs', views.statsSpammeurs, name="statsSpammeurs"),
    url(r'^stats/mec/ou/fille/de/nom/(?P<id_pers>[0-9]+)', views.statsMec, name="statsMec"),
]

SpamWeb/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from SpamWeb import settings

urlpatterns = [
    url(r'^user/', include('userManager.urls', namespace='userManager')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^jacques/a/dit/idea/', include('jacquesIdea.urls', namespace='jacquesIdea')),
    url(r'^spamConso/', include('spamConso.urls', namespace='spamConso')),
    url(r'^spamusic/', include('spamusic.urls', namespace='spamusic')),
    url(r'^spamCompte/', include('SpamCompte.urls', namespace='spamCompte')),
    url(r'^(?i)spamAlyzer/', include('SpamAlyzer.urls', namespace='SpamAlyzer')),
    url(r'^$', RedirectView.as_view(pattern_name='home:index', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SpamAlyzer/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models


class UtilisateurStats(models.Model):
    nom_fb = models.CharField(max_length=250, unique=True)

    def get_mots_plus_utilises(self, nb = 0):
        all_mots_tris = MotScore.objects.filter(user = self).order_by("-score")
        if nb != 0:
            all_mots_tris = all_mots_tris[:nb]
        return all_mots_tris

    def __str__(self):
        return "{0}".format(self.nom_fb)


class MotScore(models.Model):
    user = models.ForeignKey(UtilisateurStats)

    mot = models.CharField(max_length=500)
    score = models.IntegerField(default=0, null=False)
    class Meta:
        unique_together = ("user", "mot")

    def __str__(self):
        return "{0} ({1}) ({2})".format(self.mot, self.score, self.user)

class FichierSoumis(models.Model):
    auteur = models.ForeignKey(User)
    date_depot = models.DateField(auto_now_add=True)
    date_fichier = models.DateField(null=False, auto_now_add=False)
    fichier = models.FileField(upload_to='uploads/SpamAlyzer/%Y-%m-%d/')

class Message(models.Model):
    texte = models.CharField(max_length=5000, null=True)
    auteur = models.ForeignKey(UtilisateurStats)
    date = models.DateTimeField()
    file = models.ForeignKey(FichierSoumis)

    def __str__(self):
        return "{0} (le {1})".format(self.texte, self.date)

SpamAlyzer/forms.py
__author__ = 'david'

from django import forms

from SpamAlyzer.models import FichierSoumis


class FichierSoumisForm(forms.ModelForm):
    class Meta:
        model = FichierSoumis
        fields = ["fichier"]

SpamAlyzer/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response
from SpamAlyzer.forms import FichierSoumisForm
from SpamAlyzer import analyzer, models
from django.http import Http404

from lxml import etree
from threading import Thread
from home.log import add_log
import traceback
from SpamAlyzer.StatsHelper import StatsHelper

@login_required
def index(request):
    # If POST, then an upload has been made
    context = {}
    if request.method == "POST":
        form = FichierSoumisForm(request.POST, request.FILES)
        if form.is_valid():
            fichier = form.save(commit=False)
            fichier.auteur = request.user

            try:
                anal = analyzer.Analyzer(fichier)
                await_t = Thread(target=await_analyze_ending, args=(anal, request.user,))
                await_t.setDaemon(True)
                await_t.start()
                fichier.save()
                context["error_message"] = "Ca bidouille ! Et ça peut prendre un peu de temps parce que je code " \
                                           "n'importe comment. Bref, ça enverra une notif' dès ça a fini de charger " \
                                           "l'internet. Merci aurevoir <3"
                return render_to_response("SpamAlyzer/message.html", context)
            except etree.DocumentInvalid:
                context["error_message"] = "Oh non! Ton fichier est tout naze. " \
                                           "Python me dit dans l'oreillette DocumentInvalid. " \
                                           "C'est triste. Et franchement, tu me déçois. Je te croyais mieux que ça."
                return render_to_response("SpamAlyzer/message.html", context)
            except:
                context["error_message"] = "Aïe aïe aïe. Je ne saurais pas te dire ce qu'il s'est passé. Enfin bon, " \
                                           "de toute façon je ne suis qu'un texte écrit en dur dans le code par " \
                                           "David. " \
                                           "Normal que je ne pas déduire grand chose de l'erreur. " \
                                           "Mais voilà le message de l'exception si ça peut t'aider. (mais vu que " \
                                           "t'es nul(le), envoie ça à David. Il saura débugger, mieux que toi, " \
                                           "sa merde qu'il a pondu) : <pre>{0}</pre>".format(traceback.format_exc())
                return render_to_response("SpamAlyzer/message.html", context)
        else:
            context["error_message"] = "Oh non! Ton fichier est tout naze. " \
                                       "Python me dit dans l'oreillette que le formulaire n'est pas valide. " \
                                       "C'est triste. Et franchement, tu me déçois. Je te croyais mieux que ça."
            return render_to_response("SpamAlyzer/message.html", context)
    # No POST made, normal
    else:
        context["conversation"] = None
        form = FichierSoumisForm()

    context["form"] = form
    return render(request, 'SpamAlyzer/index.html', context)

def await_analyze_ending(analyzer, user):
    t = Thread(target=analyzer.analyze_the_spam_muhaha())
    t.setDaemon(True)
    t.start()
    t.join()
    add_log(text="{0} a déposé une archive Facebook pour alimenter la conversation du spam ! "
                 "Sa contribution nous a apporté {1} messages que le SpamWeb ne référençait pas encore. "
                 "Merci !".format(user, analyzer.new_messages),
            app="SpamAlyzer",
            log_type="SpamAlyzer_depot_archive",
            user=user)

@login_required
def conversation(request, num_page):
    num_page = int(num_page)
    NB_MSG_PAR_PAGE = 200
    context = { "conversation": None }
    messages = models.Message.objects.order_by("-date")
    nb_messages = messages.count()
    if nb_messages != 0:
        nb_pages = int(nb_messages / NB_MSG_PAR_PAGE) + 1
        if num_page > nb_pages:
            raise Http404("Invalid page number.")
        first_message = (num_page - 1) * NB_MSG_PAR_PAGE
        last_message = num_page * NB_MSG_PAR_PAGE
        if last_message > nb_messages:
            last_message = nb_messages
        context["conversation"] = messages[first_message:last_message]
        context["num_page"] = num_page
        context["nb_pages"] = nb_pages

    return render(request, "SpamAlyzer/conversation.html", context)

@login_required
def historique(request):
    context = {}
    all_depots = models.FichierSoumis.objects.order_by("-date_depot")
    if all_depots.count() != 0:
        context["depots"] = all_depots

    return render(request, "SpamAlyzer/historiqueDepot.html", context)

@login_required
def statsGlobales(request):
    stats = StatsHelper()
    context = {
        "nb_messages" : stats.nb_messages,
        "nb_pouces": stats.nb_pouces,
        "graphe_user_most_msg": stats.graphe_msg_per_user,
        "graphe_most_used_words": stats.graphe_most_used_words,
        "graphe_nb_msg_per_date": stats.graphe_nb_msg_per_date,
        "stats_type_for_menu": "SpamAlyzer/statsG",
        "cest_pour_qui": "la conversation"
    }

    return render(request, "SpamAlyzer/stats.html", context)


@login_required
def statsSpammeurs(request):
    spammeurs = []
    for spammeur in models.UtilisateurStats.objects.all():
        spammeurs.append(spammeur)
    return render(request, "SpamAlyzer/choixSpammeur.html", {"spammeurs": spammeurs})


def statsMec(request, id_pers):
    mecs = models.UtilisateurStats.objects.filter(id = id_pers)
    if mecs.count() == 0:
        return render(request, "SpamAlyzer/stats.html", {"error_message": "Utilisateur inconnu"})
    mec = mecs[0]

    stats = StatsHelper(mec)
    context = {
        "cest_pour_qui": mec.nom_fb,
        "nb_messages" : stats.nb_messages,
        "nb_pouces": stats.nb_pouces,
        "graphe_most_used_words": stats.graphe_most_used_words,
        "graphe_nb_msg_per_date": stats.graphe_nb_msg_per_date,
        "stats_type_for_menu": "SpamAlyzer/statsU",
    }

    return render(request, "SpamAlyzer/stats.html", context)

SpamAlyzer/templates/SpamAlyzer/choixSpammeur.html
{% extends "SpamAlyzer/layout.html" %}
{% load staticfiles %}

<!-- page head title -->
{% block base_title %}{{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}{{ block.super }}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}{{ block.super }}{% endblock %}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="SpamAlyzer/statsU" only %}
{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='SpamAlyzer' only %}
{% endblock %}

{% block page_header_addons %}
{% endblock %}

{% block page_footer_addons %}
    <script>
        $(function(){
           var hashCode = function (s) {
                return s.split("").reduce(function (a, b) {
                    a = ((a << 5) - a) + b.charCodeAt(0);
                    return a & a
                }, 0);
            };

            //coloration label
            var COLORS = ["btn-info", "btn-danger", "btn-default", "btn-primary", "btn-success", "btn-warning", "bg-maroon", "bg-purple", "bg-navy", "bg-olive", "bg-orange"];
            $(".btn-spammeur").each(function () {
                var $this = $(this);
                var text = $this.text();
                var hash = Math.abs(hashCode(text))%COLORS.length;
                $this.addClass(COLORS[hash]);
            });
        });
    </script>
{% endblock %}

{% block body %}
    <p class="well">Sélectionne ton(a) spammeur(euse) préféré(e) :D</p>
    <div class="row btn-">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
            <div class="row">
                {% for s in spammeurs %}
                    <div class="col-xs-12 col-md-6">
                        <a href="{% url "SpamAlyzer:statsMec" s.id %}" class="btn-spammeur btn">{{ s.nom_fb }}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

SpamAlyzer/templates/SpamAlyzer/conversation.html
{% extends "SpamAlyzer/layout.html" %}
{% load staticfiles %}

<!-- page head title -->
{% block base_title %}La Conversation | {{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}La Conversation | {{ block.super }}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}{{ block.super }}{% endblock %}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="SpamAlyzer/conversation" only %}
{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='SpamAlyzer' only %}
{% endblock %}

{% block page_header_addons %}
{% endblock %}

{% block page_footer_addons %}
{% endblock %}

{% block body %}
    <p class="well">Voici la seule et l'unique conversation du SpamNocturne!</p>

    {% if conversation %}
        <div class="choix_page row">
            {% if num_page != 1 %}
                <a href="{% url "SpamAlyzer:conversation" 1 %}" class="col-xs-1 col-xs-offset-1 text-right"><i
                        class="fa fa-angle-double-left"></i></a>
                <a href="{% url "SpamAlyzer:conversation" num_page|add:"-1" %}" class="col-xs-1 text-right"><i
                        class="fa fa-angle-left"></i></a>
            {% else %}
                <div class="col-xs-3"></div>
            {% endif %}
            <div class="col-xs-6 text-center">
                <strong>{{ num_page }}</strong>
            </div>
            {% if num_page < nb_pages %}
                <a href="{% url "SpamAlyzer:conversation" num_page|add:"1" %}" class="col-xs-1 text-left"><i
                        class="fa fa-angle-right"></i></a>
                <a href="{% url "SpamAlyzer:conversation" nb_pages %}" class="col-xs-1 text-left"><i
                        class="fa fa-angle-double-right"></i></a>
            {% else %}
                <div class="col-xs-3"></div>
            {% endif %}
        </div>
        <div class="conversation row">
            {% for m in conversation %}
                <div class="media message col-xs-12 col-xs-offset-0 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
                    <div class="media-left media-top">
                        <a href="#">
                            <img src="{% static 'userManager/avatar_defaut.jpg' %}" class="user-image" alt="User Image"/>
                        </a>
                    </div>
                    <div class="media-body">
                        <div class="row">
                            <div class="auteur col-xs-6">
                                {{ m.auteur.nom_fb }}
                            </div>
                            <div class="date text-right col-xs-6">
                                {{ m.date }}
                            </div>
                        </div>
                        <div class="row">
                            <p class="text col-xs-12">
                                {% if m.texte %}
                                    {{ m.texte }}
                                {% else %}
                                    <img src="https://fbstatic-a.akamaihd.net/rsrc.php/ya/r/FwHVs2eE5cr.svg"
                                         class="pouce img-polaroid img-responsive"/><i class="ou_pas">(ou pas)</i>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="choix_page row">
            {% if num_page != 1 %}
                <a href="{% url "SpamAlyzer:conversation" 1 %}" class="col-xs-1 col-xs-offset-1 text-right"><i
                        class="fa fa-angle-double-left"></i></a>
                <a href="{% url "SpamAlyzer:conversation" num_page|add:"-1" %}" class="col-xs-1 text-right"><i
                        class="fa fa-angle-left"></i></a>
            {% else %}
                <div class="col-xs-3"></div>
            {% endif %}
            <div class="col-xs-6 text-center">
                <strong>{{ num_page }}</strong>
            </div>
            {% if num_page < nb_pages %}
                <a href="{% url "SpamAlyzer:conversation" num_page|add:"1" %}" class="col-xs-1 text-left"><i
                        class="fa fa-angle-right"></i></a>
                <a href="{% url "SpamAlyzer:conversation" nb_pages %}" class="col-xs-1 text-left"><i
                        class="fa fa-angle-double-right"></i></a>
            {% else %}
                <div class="col-xs-3"></div>
            {% endif %}
        </div>
    {% else %}
        <div class="row">
            <p class="no_element_found_wesh col-xs-12">
                Il semblerait qu'il n'y ait aucun message du spam dans le base de dounnées! C'est un scandale!
                Je t'ordonne de demander ton archive Facebook à Facebook pour charger la conversation! Saperlipopette :D
            </p>
        </div>
    {% endif %}
{% endblock %}

SpamAlyzer/templates/SpamAlyzer/historiqueDepot.html
{% extends "SpamAlyzer/layout.html" %}
{% load staticfiles %}

<!-- page head title -->
{% block base_title %}{{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}{{ block.super }}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}{{ block.super }}{% endblock %}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="SpamAlyzer/histoDepot" only %}
{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='SpamAlyzer' only %}
{% endblock %}

{% block page_header_addons %}
    <link rel="stylesheet" type="text/css" href="{% static 'SpamAlyzer/css/index.css' %}">
{% endblock %}

{% block page_footer_addons %}
{% endblock %}

{% block body %}
    <p class="well">Mais qui a donc déposé ces magnifiques archives pour que nous puissions admirer la conversation
        depuis le SpamWeb ?!</p>
    {% if depots %}
        <div class="depots row">
            {% for d in depots %}
                <div class="media depot col-xs-12">
                    <div class="media-left media-middle">
                        <a href="#">
                            <span class="glyphicon glyphicon-folder-open"></span>
                        </a>
                    </div>
                    <div class="media-body">
                        <div class="auteur">
                            {{ d.auteur }}
                        </div>
                        <div class="date">
                            déposé le {{ d.date_depot }}
                        </div>
                        <div class="date_fichier">
                            Dernier message de ce dépot le {{ d.date_fichier }}.
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="no_element_found_wesh">Oh non! Il n'y a aucune archive de déposée! Vite! Viens par <a
                href="{% url "SpamAlyzer:index" %}">là</a> et upload la tienne.</p>
    {% endif %}
{% endblock %}

SpamAlyzer/templates/SpamAlyzer/index.html
{% extends "SpamAlyzer/layout.html" %}
{% load staticfiles %}

<!-- page head title -->
{% block base_title %}{{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}{{ block.super }}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}{{ block.super }}{% endblock %}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="SpamAlyzer/depot" only %}
{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='SpamAlyzer' only %}
{% endblock %}

{% block page_header_addons %}
    <link rel="stylesheet" type="text/css" href="{% static 'SpamAlyzer/css/dropzone.css' %}">
{% endblock %}

{% block page_footer_addons %}
    <script src="{% static 'SpamAlyzer/js/dropzone.js' %}"></script>
    <script type="text/javascript">
        Dropzone.options.myDropzone = {
            // Load dropped file directly (POST request)
            autoProcessQueue: true,
            maxFilesize: 40, // MegaBytes
            paramName: "fichier",

            init: function() {
                this.on("addedfile", function() {
                    // If new file is dropped, replace old one
                    if (this.files[1] != null) {
                        this.removeFile(this.files[0]);
                    }

                    document.getElementById("dz-message").setAttribute("style", "display:none;");
                });
            },

            success: function(file, result) {
                resultHtml = "";
                if ($(result).attr("id") == "error-container") {
                    resultHtml = result;
                }
                $("#message").html(resultHtml);
            }
        };
    </script>
{% endblock %}

{% block body %}
    <p class="well" >Charge ton fichier messages.htm de ton archive Facebook et analyse le spam !<br>L'analyse de la discussion peut être long, avant de déposer ton fichier vérifie que ton archive aura quelque chose à apporter a la discussion en consultant la date du <a href="{% url 'SpamAlyzer:histoDepot' %}">dernier dépot</a></p>
    <section class="row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
            <form action="{% url 'SpamAlyzer:index' %}" method="post" enctype="multipart/form-data" class="dropzone dz-clickable" id="myDropzone">
                <p class="dz-message" id="dz-message">
                    Pose ton archive de messages FB ici !
                </p>
                <!-- if dropzone.js not supported, creates these elements -->
                <div class="fallback">
                    <input name="fichier" type="file" />
                    <input type="submit" value="Upload"/>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </section>

    <div id="message"/>

    {%  if conversation %}

    {% endif %}
{% endblock %}

SpamAlyzer/templates/SpamAlyzer/layout.html
{% extends "LTE/base.html" %}
{% load staticfiles %}

{# CE TEMPLATE SERT DE MODELE POUR ECRIRE UN LAYOUT DANS VOTRE APP #}
{# IL PRESENTE TOUS LES BLOCKS QUE L'ON PEUT (RE-)DEFINIR EN HERITANT DE BASE.HTML #}
{# LES BLOCKS COMMENTES SONT PRESENTS DANS BASE.HTML MAIS N'ONT NORMALEMENT PAS BESOIN D'ETRE MODIFIES #}

<!-- modifie la couleur du site. les classes disponibles sont :
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  NB : Elles existent toutes en version "light", exemple : "skin-blue-light"
   La version light change le menu de gauche en blanc -->
{% block body_skin_class %}skin-green-light{%  endblock %}
<!-- changez block-super en la couleur de votre app -->

<!--
----    HEAD
---->
<!-- page head title -->
{% block base_title %}SpamAlyzer | {{ block.super }}{% endblock %}

<!-- here add you own stylesheet and scripts in header -->
{% block base_header_addons %}
    <link rel="stylesheet" type="text/css" href="{% static 'SpamAlyzer/css/spamalyzer.css' %}">
    <!-- Here : addons for the layout, in the whole App -->
    {% block page_header_addons %}
    {% endblock %}
{% endblock %}

<!-- here add you own stylesheet and scripts in footer-->
{% block base_footer_addons %}
    <!-- Here : addons for the layout, in the whole App-->
    {% block page_footer_addons %}
    {% endblock %}
{% endblock %}


<!--
----    TOP NAVBAR
---->
<!-- url of the home page -->
{# block base_index_url #}

 <!-- mini logo for sidebar mini 50x50 pixels -->
{# block base_mini_logo #}

<!-- logo for regular state and mobile devices -->
{# block base_logo #}

<!-- top right dropdowns navigation -->
{# block base_top_navbar #}

<!-- top right dropdown for user profile -->
{# block base_top_navbar_user #}

<!-- top right in navbar toggle to display controls & settings -->
{# block base_top_navbar_control_button #}


<!--
----    LEFT SIDEBAR
---->
<!-- Left Sidebar user panel  -->
{# block base_left_sidebar_user_panel #}

<!-- Left Sidebar Search Form-->
{# block base_left_sidebar_search_form #}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="SpamAlyzer" only %}
{% endblock %}


<!--
----    PAGE CONTENT HEADER
---->
<!-- Page content header title -->
{% block base_content_header_title %}SpamAlyzer{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}Redécouvre la légendaire discussion du SpamNocture grâce à l'archive Facebook !{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='SpamAlyzer' only %}
{% endblock %}


<!--
----    RIGHT SIDEBAR
---->
<!-- Right Sidebar List of tabs -->
{# block base_right_sidebar_tabs #}

<!-- Right sidebar Contents of tabs -->
{# block base_right_sidebar_contents #}


<!--
----    FOOTER
---->
{# block base_footer #}

<!--
----    PAGE CONTENT BODY
---->
<!-- Page content - body -->
{% block body %}

{% endblock %}

SpamAlyzer/templates/SpamAlyzer/message.html
<p id="error-container" class="error">
    {{ error_message }}
</p>