LTE/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /LTE/
    url(r'^$', views.index, name='index'),
]

SpamWeb/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from SpamWeb import settings

urlpatterns = [
    url(r'^user/', include('userManager.urls', namespace='userManager')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^jacques/a/dit/idea/', include('jacquesIdea.urls', namespace='jacquesIdea')),
    url(r'^spamConso/', include('spamConso.urls', namespace='spamConso')),
    url(r'^spamusic/', include('spamusic.urls', namespace='spamusic')),
    url(r'^spamCompte/', include('SpamCompte.urls', namespace='spamCompte')),
    url(r'^(?i)spamAlyzer/', include('SpamAlyzer.urls', namespace='SpamAlyzer')),
    url(r'^$', RedirectView.as_view(pattern_name='home:index', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spamusic/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views, ajax

urlpatterns = [
    # ex: /spamusic/OAuthAuthentification
    # url(r'^OAuthAuthentification', views.OAuthAuthentification, name='OAuthAuthentification'),
    # ex: /spamusic/OAuthReturn
    url(r'^OAuthReturn', views.OAuthReturn, name='OAuthReturn'),

    url(r'^ajax/sm_ap/', ajax.ajax_ajouter_playlist, name='ajax_ajouter_playlist'),
    url(r'^ajax/sm_dp/', ajax.ajax_details_playlist, name='ajax_details_playlist'),
    url(r'^ajax/sm_pi/', ajax.ajax_playlistitems, name='ajax_playlistitems'),
    url(r'^ajax/sm_rv/', ajax.ajax_rechercher_videos, name='ajax_rechercher_videos'),
    url(r'^ajax/sm_avtp/', ajax.ajax_add_video_to_playlist, name='ajax_add_video_to_playlist'),


    # ex: /spamusic/
    url(r'^', views.index, name='index'),
]

spamusic/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models

from oauth2client.django_orm import FlowField
from oauth2client.django_orm import CredentialsField

# Cette classe permet de stocker les credentials et aurorisation pour l'OAuth2
# Nottement pour la communication avec la Youtube API V3
# Comme l'objectif de spamusic est d'avoir une playlist collaborative,
#   cette table ne servira que pour un seul utilisateur
# Cet user doit exister en base, être admin et se nommer 'spamadmin' avec le mot de passe 'spamnocturne'
#  TODO FIXTURES POUR CREER L'ADMIN PROPRIETAIRE DE LA PLAYLIST


class CredentialsYoutubeModel(models.Model):
    id = models.OneToOneField(User, primary_key=True)
    credential = CredentialsField()

spamusic/views.py
from .models import CredentialsYoutubeModel
from SpamWeb import settings
from . import functions as f

from django.shortcuts import redirect, render

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
from oauth2client import xsrfutil
from oauth2client.django_orm import Storage




# VIEWS

@login_required
def OAuthReturn(request):
    master = f.get_youtube_master()
    if not xsrfutil.validate_token(settings.SECRET_KEY.encode('latin1'), request.REQUEST['state'].encode('latin1'),
                                   master):
        return HttpResponseBadRequest()
    credential = f.get_flow().step2_exchange(request.REQUEST)
    storage = Storage(CredentialsYoutubeModel, 'id', master, 'credential')
    storage.put(credential)
    return redirect('spamusic:index')


@login_required
def index(request):

    # vérifications d'accès à l'API
    master = f.get_youtube_master()
    check = f.check_youtube_master(request=request, master=master)
    if check['status'] is False:
        return check['value']
    check = f.check_api_token(request=request, master=master)
    if check['status'] is False:
        return check['value']
    else:
        credential = check['value']

    if request.user.is_superuser:
        admin = "Vous êtes un admin !"
    else:
        admin = "Vous n'etes pas un admin !"

    youtube = f.build_youtube(credential)

    playlist_list = f.playlist_list(youtube)
    '''
    playlist_list = {
        "items": [
            {
                "id": "PLFp2-gAWp2eVjZYkT502Xd0tMHFD0YjP9",
                "snippet": {
                    "publishedAt": "2015-07-10T23:57:32.000Z",
                    "channelId": "UC8iUi9DiP_Nr6uAuo7W74XQ",
                    "title": "Test spamweb",
                    "description": "",
                    "thumbnails": {
                        "default": {
                            "url": "https://i.ytimg.com/vi/JhGkt6PQQ8E/default.jpg",
                            "width": 120,
                            "height": 90
                        },
                        "medium": {
                            "url": "https://i.ytimg.com/vi/JhGkt6PQQ8E/mqdefault.jpg",
                            "width": 320,
                            "height": 180
                        },
                        "high": {
                            "url": "https://i.ytimg.com/vi/JhGkt6PQQ8E/hqdefault.jpg",
                            "width": 480,
                            "height": 360
                        },
                        "standard": {
                            "url": "https://i.ytimg.com/vi/JhGkt6PQQ8E/sddefault.jpg",
                            "width": 640,
                            "height": 480
                        }
                    },
                    "channelTitle": "SpamWeb",
                    "localized": {
                        "title": "Test spamweb",
                        "description": ""
                    }
                },
                "contentDetails": {
                    "itemCount": 4
                }
            }
        ]
    }
    '''
    yt_message = ""
    context = {
        'admin': admin,
        'yt_message': yt_message,
        'playlist_list': playlist_list,
    }
    return render(request, 'spamusic/index.html', context)

spamusic/templates/spamusic/control-sidebar-playlist.html
<li class=""  >
    <a href="#" class="playlist-play-link" data-playlistID="{{ playlist.id }}">
        <div class="control-sidebar-playlist" style="background-image: url('{{ playlist.snippet.thumbnails.medium.url }}')">
            <div class="overlay">
                <i class="fa fa-play"></i>
            </div>
            <div class="menu-info no-margin playlist-info">
                <h4 class="control-sidebar-subheading">{{ playlist.snippet.title }}</h4>
                <p>{{ playlist.contentDetails.itemCount }} Vidéo(s)</p>
            </div>
        </div>
    </a>
</li>

spamusic/templates/spamusic/index.html
{% extends 'spamusic/layout.html' %}

{% load staticfiles %}

<!-- page head title -->
{% block base_title %}Playlist | {{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}Les playlists | {{ block.super }}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}{{ block.super }}{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='spamusic' only %}
{% endblock %}

{% block page_header_addons %}
{% endblock %}

{% block page_footer_addons %}
    <!-- AdminLTE App -->
    <script>
    //URLS parametre globaux pour l'ajax du script
        URLS = {
            ajax_ajouter_playlist: "{% url 'spamusic:ajax_ajouter_playlist' %}",
            ajax_playlistitems: "{% url 'spamusic:ajax_playlistitems' %}",
            ajax_details_playlist: "{% url 'spamusic:ajax_details_playlist' %}",
            ajax_rechercher_videos: "{% url 'spamusic:ajax_rechercher_videos' %}",
            ajax_add_video_to_playlist: "{% url 'spamusic:ajax_add_video_to_playlist' %}"
        };
    </script>
    <script src="{% static 'spamusic/js/spamusic-index.js' %}" type="text/javascript"></script>
{% endblock %}


{% block page_right_sidebar_contents %}
    <div class="sidebar-form form-input-black" id="add-playlist-form">
        <div class="input-group">
            <input name="name" class="form-control" placeholder="Nouvelle playlist" type="text" onKeyPress="if(event.keyCode == 13){$('#add-playlist-btn').click()}">
            <span class="input-group-btn">
                <button type="button" name="add-playlist" id="add-playlist-btn" class="btn btn-flat"><i class="fa fa-plus"></i></button>
            </span>
        </div>
    </div>
    <ul class="control-sidebar-menu" id="control-playlist-list">
        {% for playlist in playlist_list.items %}
            {% include 'spamusic/control-sidebar-playlist.html' with playlist=playlist %}
        {% endfor %}
    </ul>
{% endblock %}

{% block body %}
    <div id="main-content">
        <div class="row">
            <div class="jumbotron col-xs-10 col-xs-offset-1">
                <h1>Bienvenue sur Spamusic !</h1>
                <p>Partagez votre musique en créant et modifiant les playlist du <b>Spam</b>Web !</p>
                <p>{{ yt_message }}</p>
                <button class="btn btn-default" data-toggle="control-sidebar" onclick="$('a[href=\'#control-sidebar-playlist-tab\']').click();">Voir les playlist</button>
            </div>
        </div>
    </div>
{% endblock %}

spamusic/templates/spamusic/layout.html
{% extends "LTE/base.html" %}
{% load staticfiles %}

{# CE TEMPLATE SERT DE MODELE POUR ECRIRE UN LAYOUT DANS VOTRE APP #}
{# IL PRESENTE TOUS LES BLOCKS QUE L'ON PEUT (RE-)DEFINIR EN HERITANT DE BASE.HTML #}
{# LES BLOCKS COMMENTES SONT PRESENTS DANS BASE.HTML MAIS N'ONT NORMALEMENT PAS BESOIN D'ETRE MODIFIES #}

<!-- modifie la couleur du site. les classes disponibles sont :
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  NB : Elles existent toutes en version "light", exemple : "skin-blue-light"
   La version light change le menu de gauche en blanc -->
{% block body_skin_class %}skin-red{%  endblock %}
<!-- changez block-super en la couleur de votre app -->

<!--
----    HEAD
---->
<!-- page head title -->
{% block base_title %}Spamusic | {{ block.super }}{% endblock %}

<!-- here add you own stylesheet and scripts in header -->
{% block base_header_addons %}
    <!-- Here : addons for the layout, in the whole App -->
    <link href="{% static 'spamusic/css/spamusic.css' %}" rel="stylesheet" type="text/css" />
    {% block page_header_addons %}
    {% endblock %}
{% endblock %}

<!-- here add you own stylesheet and scripts in footer-->
{% block base_footer_addons %}
    <!-- Here : addons for the layout, in the whole App-->
    {% block page_footer_addons %}
    {% endblock %}
{% endblock %}


<!--
----    TOP NAVBAR
---->
<!-- url of the home page -->
{# block base_index_url #}

 <!-- mini logo for sidebar mini 50x50 pixels -->
{# block base_mini_logo #}

<!-- logo for regular state and mobile devices -->
{# block base_logo #}

<!-- top right dropdowns navigation -->
{# block base_top_navbar #}

<!-- top right dropdown for user profile -->
{# block base_top_navbar_user #}

<!-- top right in navbar toggle to display controls & settings -->
{# block base_top_navbar_control_button #}


<!--
----    LEFT SIDEBAR
---->
<!-- Left Sidebar user panel  -->
{# block base_left_sidebar_user_panel #}

<!-- Left Sidebar Search Form-->
{# block base_left_sidebar_search_form #}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="spamusic" only %}
{% endblock %}


<!--
----    PAGE CONTENT HEADER
---->
<!-- Page content header title -->
{% block base_content_header_title %}Spamusic{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}Y'a du son, c'est ça qu'est bon !{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='Spamusic' only %}
{% endblock %}


<!--
----    RIGHT SIDEBAR
---->
<!-- Right Sidebar List of tabs -->
{# block base_right_sidebar_tabs #}
{% block base_right_sidebar_tabs %}
    <li><a href="#control-sidebar-playlist-tab" data-toggle="tab"><i class="fa fa-youtube"></i></a></li>
{% endblock %}

<!-- Right sidebar Contents of tabs -->
{# block base_right_sidebar_contents #}
{% block base_right_sidebar_contents %}
    <div class="tab-pane" id="control-sidebar-playlist-tab">
        <p class="text-center row"><a class="btn bg-navy btn-xs btn-flat btn-block" href="#" data-toggle="control-sidebar" title="Fermer les playlist">Fermer&nbsp;<i class="fa fa-times"></i></a></p>
        <h3 class="control-sidebar-heading">Playlist du <b>Spam</b>Web</h3>
        {% block page_right_sidebar_contents %}
        {% endblock %}
    </div>
{% endblock %}

<!--
----    FOOTER
---->
{# block base_footer #}

<!--
----    PAGE CONTENT BODY
---->
<!-- Page content - body -->
{% block body %}
{% endblock %}

spamusic/templates/spamusic/main-content.html
<div class="row">
    <div class="col-xs-12" id="yt-playlist-header">
        <h2>
            <button class="btn btn-default pull-right" data-toggle="control-sidebar-playlist">Voir les playlist</button>
            <button id="refresh-playlist-btn" class="btn btn-gray bg-gray pull-right" data-iframe="$('#yt-playlist-header iframe')" data-toggle="tooltip" title="Actualiser le lecteur"><i class="fa fa-refresh"></i></button>
            Playlist : {{ playlist.snippet.title }}
        </h2>
    </div>
    <div class="bg-black-gradient col-xs-12 no-padding">
        <div class="video-wrapper">
            <div class="video-container">
                {% autoescape off %}
                    {{ playlist.player.embedHtml }}
                {% endautoescape %}
            </div>
        </div>
    </div>
</div>
<div class="row dark-themed">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified black-nav">
        <li class="active"><a aria-expanded="true" href="#yt-tab-infos" data-toggle="tab">Informations</a></li>
        <li><a href="#yt-tab-videos" data-toggle="tab">Vidéos</a></li>
        <li><a href="#yt-tab-search" data-toggle="tab">Rechercher</a></li>
    </ul>
    <div class="col-xs-12 black-tab-content tab-content">
        <!-- Tab panes -->

            <!-- Infos tab content -->
            <div class="tab-pane active" id="yt-tab-infos">
                <h2>Informations</h2>
                <p>Nom de la playlist : {{ playlist.snippet.title }}</p>
                <p>Description : {{ playlist.snippet.description }}</p>
                <p>Nombre de vidéos : {{ playlist.contentDetails.itemCount }}</p>
                <p>Créée le : {{ playlist.snippet.publishedAt|date:"d F Y" }}</p>
                <p>Propriétaire : {{ playlist.snippet.channelTitle }}</p>
            </div>
            <!-- /.tab-pane -->
            <!-- Videos tab content -->
            <div class="tab-pane" id="yt-tab-videos">
               <h2>Vidéos de {{ playlist.snippet.title }}</h2>
            </div>
            <!-- /.tab-pane -->
            <!-- Search tab content -->
            <div class="tab-pane" id="yt-tab-search">
                <h3>Rechercher de nouvelles vidéos</h3>
                <div class="sidebar-form form-input-black" id="search-video-form">
                    <div class="input-group">
                        <input name="q" class="form-control" placeholder="Rechercher ..." type="text" onKeyPress="if(event.keyCode == 13){$('#search-video-btn').click()}">
                        <span class="input-group-btn">
                            <button type="button" name="search-video" id="search-video-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </div>
                <div id="yt-tab-search-results" data-playlistId="{{ playlist.id }}">

                </div>
            </div>
            <!-- /.tab-pane -->
    </div>
</div>

spamusic/templates/spamusic/message.html
{% extends 'spamusic/layout.html' %}

<!-- page head title -->
{% block base_title %}Message | {{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}{% if title %}{{ title }}{% else %}Message{% endif %}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}Il s'est passé quelque chose !{% endblock %}


{% block body %}
    <div class="jumbotron">
  <h1>{{ title }}</h1>
  <p>{{ message }}</p>
    {%  if url_for_admin %}
  <p><a class="btn btn-primary btn-lg" href="{{ url_for_admin }}" role="button">C'est par ici la suite !</a></p>
    {% endif %}
    {% if url_for_user %}
  <p><a class="btn btn-primary btn-lg" href="{{ url_for_user }}" role="button">C'est fait ! Allez retour case départ</a></p>
    {% endif %}
</div>
{% endblock %}

spamusic/templates/spamusic/new-video.html
 <li class="row media">
    <div class="col-xs-12 col-lg-10 col-lg-offset-1">
          <div class="media-left media-middle">
            <a href="#" data-playlistItemId="{{ playlist_item.id }}" data-playlistId="{{ playlist_item.snippet.playlistId }}" data-videoId="{{ playlist_item.snippet.resourceId.videoId }}">
              <img class="media-object visible-xs visible-sm" src="{{ playlist_item.snippet.thumbnails.default.url }}" alt="Thumbnail-default">
              <img class="media-object visible-md visible-lg" src="{{ playlist_item.snippet.thumbnails.medium.url }}" alt="Thumbnail-medium">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading">{{ playlist_item.snippet.title }}</h4>
                <p>Ajoutée le : {{ playlist_item.snippet.publishedAt|date:"d F Y" }}</p>
          </div>
    </div>
</li>

spamusic/templates/spamusic/playlist-videos.html
<ul id="playlistItem-list" class="media-list">
    {% for playlist_item in playlist_items.items %}
        <li class="row media">
            <div class="col-xs-12 col-md-10 col-md-offset-1">
                  <div class="media-left media-middle">
                    <a href="#" data-playlistItemId="{{ playlist_item.id }}" data-playlistId="{{ playlist_item.snippet.playlistId }}" data-videoId="{{ playlist_item.snippet.resourceId.videoId }}">
                      <img class="media-object visible-xs visible-sm visible-md" src="{{ playlist_item.snippet.thumbnails.default.url }}" alt="Thumbnail-default">
                      <img class="media-object visible-lg" src="{{ playlist_item.snippet.thumbnails.medium.url }}" alt="Thumbnail-medium">
                    </a>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading">{{ playlist_item.snippet.title }}</h4>
                        <p>Ajoutée le : {{ playlist_item.snippet.publishedAt|date:"d F Y" }}</p>
                  </div>
            </div>
        </li>
    {% endfor %}
</ul>

spamusic/templates/spamusic/yt-tab-search-results.html
<ul id="search-result-list" class="media-list">
    {% for video in video_list.items %}
        <li class="row media">
            <div class="col-xs-12 col-md-10 col-md-offset-1">
                  <div class="media-left media-middle">
                    <a href="#" data-channelId="{{ video.snippet.channelId }}" data-videoId="{{ video.id.videoId }}">
                      <img class="media-object visible-xs visible-sm visible-md" src="{{ video.snippet.thumbnails.default.url }}" alt="Thumbnail-default">
                      <img class="media-object visible-lg" src="{{ video.snippet.thumbnails.medium.url }}" alt="Thumbnail-medium">
                    </a>
                  </div>
                  <div class="media-body">
                        <h4 class="media-heading">{{ video.snippet.title }}</h4>
                        <a href="#" class="btn btn-default pull-right add-to-playlist-btn" data-videoId="{{ video.id.videoId }}">Ajouter à la playlist</a>
                        <p>Ajoutée le : {{ video.snippet.publishedAt|date:"d F Y" }}</p>
                        <p>Chaîne YouTube : {{ video.snippet.channelTitle }}</p>
                  </div>
            </div>
        </li>
    {% endfor %}
</ul>
<a href="#" class="btn" data-q="{{ q }}" data-nextpagetoken="{{ video_list.nextPageToken }}">Page suivante ... </a>