LTE/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /LTE/
    url(r'^$', views.index, name='index'),
]

SpamAlyzer/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^conversation/spam/web/(?P<num_page>[0-9]+)', views.conversation, name="conversation"),
    url(r'^historique/depot', views.historique, name="histoDepot"),
    url(r'^stats/globales', views.statsGlobales, name="statsGlobales"),
    url(r'^stats/spammeurs', views.statsSpammeurs, name="statsSpammeurs"),
    url(r'^stats/mec/ou/fille/de/nom/(?P<id_pers>[0-9]+)', views.statsMec, name="statsMec"),
]

SpamWeb/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from SpamWeb import settings

urlpatterns = [
    url(r'^user/', include('userManager.urls', namespace='userManager')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^jacques/a/dit/idea/', include('jacquesIdea.urls', namespace='jacquesIdea')),
    url(r'^spamConso/', include('spamConso.urls', namespace='spamConso')),
    url(r'^spamusic/', include('spamusic.urls', namespace='spamusic')),
    url(r'^spamCompte/', include('SpamCompte.urls', namespace='spamCompte')),
    url(r'^(?i)spamAlyzer/', include('SpamAlyzer.urls', namespace='SpamAlyzer')),
    url(r'^$', RedirectView.as_view(pattern_name='home:index', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spamConso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^GBienBuGBienMangé', views.index, name='index'),
    url(r'^add_conso', views.add_conso, name = 'add_conso'),
    url(r'^consos', views.conso_view, name = 'conso_view'),

]

LTE/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'LTE/starter.html', {})

LTE/templates/LTE/breadcrumb.html
{# Variable a fournir : [prev1Name prev1Url [prev2Name prev2Url [...]]] current #}
{# On ne peut creer de liste ou de dictionnaire dans le template, on utilise donc des variables non obligatoire #}
<li><a href="{% url 'home:index' %}"><i class="fa fa-dashboard"></i> <b>Spam</b>Web</a></li>

{% if prev1Name and prev1Url%}
    <li><a href="{% url prev1Url %} ">{{ prev1Name }}</a></li>
    {% if prev2Name and prev2Url%}
        <li><a href="{% url prev2Url %}">{{ prev2Name }}</a></li>
        {% if prev3Name and prev3Url%}
            <li><a href="{% url prev3Url %}">{{ prev3Name }}</a></li>
            {% if prev4Name and prev4Url%}
                <li><a href="{% url prev4Url %}">{{ prev4Name }}</a></li>
            {% endif %}
        {% endif %}
    {% endif %}
{% endif %}

<li class="active">{{ current }}</li>

LTE/templates/LTE/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block login_title %}AdminLTE 2 | Log in{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.4 -->
    <link href="{% static 'LTE/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'LTE/dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'LTE/plugins/iCheck/square/blue.css' %}" rel="stylesheet" type="text/css" />

    <link rel="icon" type="image/png" href="{% static 'LTE/img/icon.png' %}" />

    {% block login_additional_stylesheet %}{% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
      {%  block login_logo %}
        <a href="../../index2.html"><b>Admin</b>LTE</a>
      {% endblock %}
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        {% block login_box_msg %}
            <p class="login-box-msg">Sign in to start your session</p>
        {%  endblock %}
        <form action="{% block login_form_action %}../../index2.html{% endblock %}" method="post">
          {% block login_form_fields %}
          <div class="form-group has-feedback">
            <input type="email" class="form-control" placeholder="Email"/>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" placeholder="Password"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          {% endblock %}
          <div class="row">
            {%  block login_form_remember_me %}
            <div class="col-xs-8">    
              <div class="checkbox icheck">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>                        
            </div><!-- /.col -->
            {% endblock %}
            {% block login_form_submit %}
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
            {% endblock %}
          </div>
        </form>
        {% block login_social_auth %}
        <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div><!-- /.social-auth-links -->
        {% endblock %}
        {% block login_password_forgotten_link %}
        <a href="#">I forgot my password</a><br>
        {% endblock %}
        {% block login_register_link %}
        <a href="register.html" class="text-center">Register a new membership</a>
        {% endblock %}

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.4 -->
    <script src="{% static 'LTE/plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'LTE/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="{% static 'LTE/plugins/iCheck/icheck.min.js' %}" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>

LTE/templates/LTE/menu.html
  <!-- Sidebar Menu -->
  <ul class="sidebar-menu">
    <li class="header">MENU PRINCIPAL</li>
    <!-- Optionally, you can add icons to the links -->
    <li {% ifequal active "jacquesIdea" %}class="active" {% endifequal %}><a href="{% url 'jacquesIdea:index' %}"><i class="fa fa-lightbulb-o"></i> <span>Idées</span></a></li>
    <li {% ifequal active "calendrier" %}class="active" {% endifequal %}><a href="#"><i class='fa fa-calendar'></i> <span>Calendrier</span></a></li>
    <li {% ifequal active "comptes" %}class="active" {% endifequal %}><a href="{% url 'spamCompte:index' %}"><i class='fa fa-euro'></i> <span>Comptes</span></a></li>
    <li class="treeview {% if "spamConso" in active %}active{% endif %}">
      <a href="#">
          <i class='fa fa-bar-chart'></i> <span>SpamConso</span> <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
        <li {% ifequal active "spamConso/index" %}class="active" {% endifequal %}><a href="{% url 'spamConso:index' %}"><i class='fa fa-plus'></i> Ajouter </a></li>
        <li {% ifequal active "spamConso/bieres" %}class="active" {% endifequal %}><a href="{% url 'spamConso:conso_view' %}?type=biere"><i class='fa fa-beer'></i> Bières</a></li>
        <li {% ifequal active "spamConso/tacos" %}class="active" {% endifequal %}><a href="{% url 'spamConso:conso_view' %}?type=tacos"><i class='fa fa-cutlery'></i> Tacos</a></li>
        <li {% ifequal active "spamConso/pouces" %}class="active" {% endifequal %}><a href="{% url 'spamConso:index' %}"><i class='fa fa-thumbs-o-up'></i> Pouces</a></li>
      </ul>
    </li>
    <li {% ifequal active "repertoire" %}class="active" {% endifequal %}><a href="#"><i class='fa fa-book'></i> <span>Répertoire</span></a></li>
    <li {% ifequal active "spamusic" %}class="active" {% endifequal %}><a href="{% url 'spamusic:index' %}"><i class='fa fa-youtube'></i> <span>Spamusic</span><!--<a class="pull-right" target="_blank" href="{% url 'spamusic:index' %}"><i class="fa fa-external-link"></i></a>--></a></li>
    <li class="treeview {% if "SpamAlyzer" in active %}active{% endif %}">
      <a href="#">
          <i class='fa fa-comments-o'></i> <span>SpamAlyzer</span> <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
        <li {% ifequal active "SpamAlyzer/depot" %}class="active" {% endifequal %}><a href="{% url 'SpamAlyzer:index' %}"><i class='fa fa-file-archive-o'></i> Dépôt d'archive</a></li>
        <li {% ifequal active "SpamAlyzer/conversation" %}class="active" {% endifequal %}><a href="{% url 'SpamAlyzer:conversation' 1 %}"><i class='fa fa-comments'></i> LA conversation</a></li>
        <li {% ifequal active "SpamAlyzer/statsG" %}class="active" {% endifequal %}><a href="{% url 'SpamAlyzer:statsGlobales' %}"><i class='fa fa-line-chart'></i> Stats globales</a></li>
        <li {% ifequal active "SpamAlyzer/statsU" %}class="active" {% endifequal %}><a href="{% url 'SpamAlyzer:statsSpammeurs' %}"><i class='fa fa-bar-chart'></i> Stats des spammeurs</a></li>
        <li {% ifequal active "SpamAlyzer/histoDepot" %}class="active" {% endifequal %}><a href="{% url 'SpamAlyzer:histoDepot' %}"><i class='fa fa-archive'></i> Historiques de dépôts</a></li>
      </ul>
    </li>
  </ul><!-- /.sidebar-menu -->

LTE/templates/LTE/page.html
{% extends "monApp/layout.html" %}
{% load staticfiles %}

<!-- page head title -->
{% block base_title %}Ma Page | {{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}Titre de ma page{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}Description de ma page{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='nomDeLaPage' prev1Name='monApp' prev1Url='monApp:index' only %}
{% endblock %}

{% block page_header_addons %}
{% endblock %}

{% block page_footer_addons %}
{% endblock %}

{% block body %}
{% endblock %}

LTE/templates/LTE/starter.html
{% extends "LTE/base.html" %}
{% load staticfiles %}

{# CE TEMPLATE SERT DE MODELE POUR ECRIRE UN LAYOUT DANS VOTRE APP #}
{# IL PRESENTE TOUS LES BLOCKS QUE L'ON PEUT (RE-)DEFINIR EN HERITANT DE BASE.HTML #}
{# LES BLOCKS COMMENTES SONT PRESENTS DANS BASE.HTML MAIS N'ONT NORMALEMENT PAS BESOIN D'ETRE MODIFIES #}

<!-- modifie la couleur du site. les classes disponibles sont :
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  NB : Elles existent toutes en version "light", exemple : "skin-blue-light"
   La version light change le menu de gauche en blanc -->
{% block body_skin_class %}{{ block.super }}{%  endblock %}
<!-- changez block-super en la couleur de votre app -->

<!--
----    HEAD
---->
<!-- page head title -->
{% block base_title %}Mon App | {{ block.super }}{% endblock %}

<!-- here add you own stylesheet and scripts in header -->
{% block base_header_addons %}
    <!-- Here : addons for the layout, in the whole App -->
    {% block page_header_addons %}
    {% endblock %}
{% endblock %}

<!-- here add you own stylesheet and scripts in footer-->
{% block base_footer_addons %}
    <!-- Here : addons for the layout, in the whole App-->
    {% block page_footer_addons %}
    {% endblock %}
{% endblock %}


<!--
----    TOP NAVBAR
---->
<!-- url of the home page -->
{# block base_index_url #}

 <!-- mini logo for sidebar mini 50x50 pixels -->
{# block base_mini_logo #}

<!-- logo for regular state and mobile devices -->
{# block base_logo #}

<!-- top right dropdowns navigation -->
{# block base_top_navbar #}

<!-- top right dropdown for user profile -->
{# block base_top_navbar_user #}

<!-- top right in navbar toggle to display controls & settings -->
{# block base_top_navbar_control_button #}


<!--
----    LEFT SIDEBAR
---->
<!-- Left Sidebar user panel  -->
{# block base_left_sidebar_user_panel #}

<!-- Left Sidebar Search Form-->
{# block base_left_sidebar_search_form #}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="monOngletActif" only %}
{% endblock %}


<!--
----    PAGE CONTENT HEADER
---->
<!-- Page content header title -->
{% block base_content_header_title %}{{ block.super }}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}{{ block.super }}{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='Mon App' only %}
{% endblock %}


<!--
----    RIGHT SIDEBAR
---->
<!-- Right Sidebar List of tabs -->
{# block base_right_sidebar_tabs #}

<!-- Right sidebar Contents of tabs -->
{# block base_right_sidebar_contents #}


<!--
----    FOOTER
---->
{# block base_footer #}

<!--
----    PAGE CONTENT BODY
---->
<!-- Page content - body -->
{% block body %}{% endblock %}