LTE/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /LTE/
    url(r'^$', views.index, name='index'),
]

SpamWeb/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from SpamWeb import settings

urlpatterns = [
    url(r'^user/', include('userManager.urls', namespace='userManager')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^jacques/a/dit/idea/', include('jacquesIdea.urls', namespace='jacquesIdea')),
    url(r'^spamConso/', include('spamConso.urls', namespace='spamConso')),
    url(r'^spamusic/', include('spamusic.urls', namespace='spamusic')),
    url(r'^spamCompte/', include('SpamCompte.urls', namespace='spamCompte')),
    url(r'^(?i)spamAlyzer/', include('SpamAlyzer.urls', namespace='SpamAlyzer')),
    url(r'^$', RedirectView.as_view(pattern_name='home:index', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spamConso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^GBienBuGBienMangé', views.index, name='index'),
    url(r'^add_conso', views.add_conso, name = 'add_conso'),
    url(r'^consos', views.conso_view, name = 'conso_view'),

]

spamConso/models.py
# -*- coding: utf-8 -*-

import datetime
from django.contrib.auth.models import User
import json
from django.db import models
from django.utils import timezone


class ConsoTag(models.Model):
    name = models.CharField(max_length=50)
    value = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return 'Tag : %s (%s)' % (self.name, self.value)


class Consommation(models.Model):
    CONSO_CHOICES = (
        ('tacos', 'Tacos'),
        ('biere', 'Biere')
    )
    type = models.CharField(max_length=20, choices=CONSO_CHOICES)
    description = models.CharField(max_length=60, blank=True, default="")
    tags = models.CharField(max_length=255, blank=True, default="")
    conso_date = models.DateTimeField()
    consommateur = models.ForeignKey(User, related_name='consommations', related_query_name="consommation")

    def __str__(self):
        return "%s a consommé %s le %s - Tag %s" % (
        self.type, self.consommateur.username, str(self.conso_date.strftime("%d/%m/%Y %H:%M:%S")), str(self.tags))

    @property
    def get_tags_as_dict(self):
        if self.tags:
            return json.loads(self.tags)
        return dict()

spamConso/forms.py
from django import forms
from .models import Consommation

class ConsoForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Consommation
        fields = ["type", "tags", "description"]
        labels = {
            'type': "Type",
            'tags': "Tags",
            'description': "Description",
        }

    def __init__(self, *args, **kwargs):
        super(ConsoForm, self).__init__(*args, **kwargs)
        self.fields['type'].widget.attrs\
            .update({
                'placeholder': "Type de conso",
                'class': 'form-control'
            })
        self.fields['description'].widget.attrs\
            .update({
                'placeholder': "C'était bon ?",
                'class': 'form-control'
            })

spamConso/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.utils import timezone
from home.log import add_log
from django.db.models import Count
from spamConso.forms import ConsoForm
from spamConso.models import Consommation, ConsoTag
import json


@login_required
def index(request):
    csrfContext = RequestContext(request)
    conso_list = Consommation.objects.order_by('conso_date')
    conso_tags = ConsoTag.objects.all()
    form = ConsoForm()
    context = {
        'conso_list': conso_list,
        'form': form,
        'conso_tags': conso_tags,
        'csrfContext': csrfContext
    }
    return render(request, 'spamConso/index.html', context)


@login_required
def add_conso(request):
    error = False
    if request.method == "POST":
        form = ConsoForm(request.POST)
        if form.is_valid():
            conso = form.save(commit=False)
            conso.conso_date = timezone.now()
            conso.consommateur = request.user
            conso.save()
            tags = json.loads(conso.tags)
            all_tags_value = ConsoTag.objects.all().values('value')
            for tag_value, tag_name in tags.items():
                # s'il y a un nouveau tag
                if not any(d['value'] == tag_value for d in all_tags_value):
                    new_tag = ConsoTag()
                    new_tag.name = tag_name
                    new_tag.value = tag_value
                    new_tag.save()
            # ajout du log
            log_type = ""
            if conso.type == "biere":
                log_type = "spamConso_add_conso_beer"
            elif conso.type == "tacos":
                log_type = "spamConso_add_conso_tacos"
            add_log(text="%s a consommé %s" % (conso.type, conso.consommateur.username),
                    app="spamConso",
                    log_type=log_type,
                    user=request.user)
        else:
            error = True
    else:
        form = ConsoForm()

    return redirect(reverse('spamConso:index'))


@login_required
def conso_view(request):
    conso_tags = ConsoTag.objects.all()
    user = User.objects.values('username', 'id')
    biere_list = Consommation.objects.filter(type=request.GET.get('type'))
    yaxis = request.GET.get('type')
    xaxis = 'rien'
    if request.GET.get('yaxis') and request.GET.get('yaxis') != 'all':
        yaxis = request.GET.get('yaxis')
        biere_list = biere_list.filter(tags__contains= request.GET.get('yaxis'))
    graphe = []
    if request.GET.get('xaxis') == 'personne':
        xaxis = 'personne'
        biere_list = biere_list.values('consommateur').annotate(total=Count('type'))
        for biere_row in biere_list:
            biere_row['username'] = user.get(id=biere_row['consommateur'])['username']
        graphe = [{'xaxis': row['username'], 'yaxis': row['total']} for row in biere_list]

    elif request.GET.get('xaxis') == 'date':
        mois = ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre']
        xaxis = 'mois'
        biere_list = biere_list.extra(select={'month': 'extract( month from conso_date )'}) \
            .values('month') \
            .annotate(total=Count('type'))
        graphe = [{'xaxis': mois[int(row['month'])- 1], 'yaxis': row['total']} for row in biere_list]

    context = {'conso_tags': conso_tags,
               'graphe': graphe,
               'xaxis': xaxis,
               'yaxis': yaxis}
    return render(request, 'spamConso/%s.html' % request.GET.get('type'), context)

spamConso/templates/spamConso/biere.html
{% extends "spamConso/layout.html" %}
{% load staticfiles %}

<!-- page head title -->
{% block base_title %}Ma Bières | {{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}#Bieres{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}Ici tu peux avoir des graphes concernant les bieres{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->

{% block page_header_addons %}
    <!-- select2 -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with prev1Url='spamConso:index' prev1Name="SpamConso" current="Bières" only %}
{% endblock %}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="spamConso/bieres" only %}
{% endblock %}

{% block page_footer_addons %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    <script>
        var mois = ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre'];
        var chartData = {
            labels: [{% for value in graphe %} "{{ value.xaxis }}" ,{% endfor %}],
            datasets: [
                {
                    label: "Biere per month dataset",
                    fillColor: "rgba(220,220,220,0.5)",
                    strokeColor: "rgba(220,220,220,0.8)",
                    highlightFill: "rgba(220,220,220,0.75)",
                    highlightStroke: "rgba(220,220,220,1)",
                    data: [{% for value in graphe %} {{ value.yaxis }}, {% endfor %}]
                }
            ]
        };

        $(function () {
            var ctx = document.getElementById("myChart").getContext("2d");
            var myChart = new Chart(ctx).Bar(chartData, {
                responsive: true,
                maintainAspectRatio: false
            });

            $('select').select2({
                width: '100%'
            });
        });
    </script>
{% endblock %}

{% block body %}
    <h3>Nombre de <b>Bières</b> #{{ yaxis }} par {{ xaxis }}</h3>
    <form action="{% url 'spamConso:conso_view' %}" method="get" class="row">
        <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-0">
        <input name="type" value="biere" hidden>
            <select name="yaxis">
                <option value="all">Tous</option>
                {% for conso_tag in conso_tags %}
                    <option value="{{ conso_tag.value }}"
                            {% ifequal conso_tag.value request.GET.yaxis %}selected="selected"{% endifequal %}>{{ conso_tag.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-0">
            <select name="xaxis">
                <option value="personne" {% ifequal "personne" request.GET.xaxis %}selected="selected"{% endifequal %}>
                    Par personne
                </option>
                <option value="date" {% ifequal "date" request.GET.xaxis %}selected="selected"{% endifequal %}>Par
                    mois
                </option>
            </select>
        </div>
        <div class="col-xs-4 col-xs-offset-4 col-md-4 col-md-offset-0">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Get !</button>
        </div>
    </form>
    <div class="row">
        <canvas id='myChart' class="col-xs-12" width="100%" height="400"></canvas>
    </div>

{% endblock %}

spamConso/templates/spamConso/index.html
{% extends "spamConso/layout.html" %}
{% load staticfiles %}


<!-- page head title -->
{% block base_title %}Nouvelle Conso | {{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}Alors on est <b>gros ?</b> | {{ block.super }}{% endblock %}

{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='Ajouter une SpamConso' prev1Name='SpamConso' prev1Url='spamConso:index' only %}
{% endblock %}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="spamConso/index" only %}
{% endblock %}

{% block page_footer_addons %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('select#id_type').select2({
                width: '100%'
            });
            $('select#conso_tag_choice').select2({
                tags: true,
                placeholder: 'Choisis ou crée un nouveau tag pour ta conso !',
                width: '100%',
                matcher: function (params, data) {
                    // If there are no search terms, return all of the data
                    if ($.trim(params.term) === '') {
                        return data;
                    }
                    // `params.term` should be the term that is used for searching
                    // `data.text` is the text that is displayed for the data object
                    if (data.text.toLowerCase().replace("-", "").indexOf(params.term.toLowerCase().replace("-", "")) > -1) {
                        return $.extend({}, data, true);
                    }

                    // Return `null` if the term should not be displayed
                    return null;
                },
                createTag: function (tag) {

                    // check if the option is already there
                    found = false;
                    $("#conso_tag_choice option").each(function () {
                        if ($.trim(tag.term).toUpperCase().replace("-", "") == $.trim($(this).text()).toUpperCase().replace("-", "")) {
                            found = true;
                        }
                    });

                    // show the suggestion only if a match was not found
                    if (!found) {
                        return {
                            id: tag.term,
                            text: tag.term,
                            isNew: true
                        };
                    }
                }
            });

            //form submit
            $("form").submit(function (e) {
                var tags_text = {};
                $(this).find("#conso_tag_choice").find("option:selected").each(function () {
                    var $this = $(this);
                    var value = $this.val().toLowerCase().replace("-", "").trim();
                    var name = $this.text().trim();
                    if (value.length && name.length) {
                        tags_text[value] = name;
                    }
                });
                // console.log(JSON.stringify(tags_text));
                $("#id_tags").val(JSON.stringify(tags_text));
            });

            var hashCode = function (s) {
                return s.split("").reduce(function (a, b) {
                    a = ((a << 5) - a) + b.charCodeAt(0);
                    return a & a
                }, 0);
            };

            //coloration label
            var LABELS_COLOR = ["label-info", "label-danger", "label-default", "label-primary", "label-success", "label-warning"];
            $("table td span.label").each(function () {
                var $this = $(this);
                var text = $this.attr("data-value");
                var hash = Math.abs(hashCode(text))%LABELS_COLOR.length;
                $this.addClass(LABELS_COLOR[hash]);
            });

        });
    </script>
{% endblock %}

{% block page_header_addons %}
    <!-- select2 -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{% block body %}
    <section class="row">
        <form action="{% url 'spamConso:add_conso' %}" method="post">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="form-group {% if form.type.errors %}has-error{% endif %}">
                    {{ form.type.label_tag }} {{ form.type }}
                    {% for error in form.type.errors %}
                        <p class="text-red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="form-group {% if form.tags.errors %}has-error{% endif %}">
                    <label for="conso_tag_choice">{{ form.tags.label }}</label>
                    {{ form.tags }}<!-- hidden tag -->
                    <select class="form-control" id="conso_tag_choice" multiple="multiple">
                        {% for conso_tag in conso_tags %}
                            <option value="{{ conso_tag.value }}">{{ conso_tag.name }}</option>
                        {% endfor %}
                    </select>
                    {% for error in form.tags.errors %}
                        <p class="text-red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="form-group {% if form.description.errors %}has-error{% endif %}">
                    {{ form.description.label_tag }} {{ form.description }}
                    {% for error in form.description.errors %}
                        <p class="text-red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-xs-4 col-xs-offset-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Ajouter</button>
            </div>
            <!-- /.col -->
            {% csrf_token %}
        </form>
    </section>
    <section class="row">
        <div class="col-xs-12">
            <table class="table table-bordered col-xs-12">
                <caption>Historique des Consommations</caption>
                <tbody>
                <tr>
                    <th>Type</th>
                    <th>Consommateur</th>
                    <th>Tags</th>
                    <th>Description</th>
                    <th>Date</th>
                </tr>
                {% for conso in conso_list.reverse %}
                    <!-- conso -->
                    <tr>
                        <td>{{ conso.type }}</td>
                        <td>{{ conso.consommateur }}</td>
                        <td>
                            {% for tag_value, tag_name in conso.get_tags_as_dict.items %}
                                <span class="label" data-value="{{ tag_value }}">{{ tag_name }}</span>&nbsp;
                            {% endfor %}
                        </td>
                        <td>{{ conso.description }}</td>
                        <td>{{ conso.conso_date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

spamConso/templates/spamConso/layout.html
{% extends "LTE/base.html" %}
{% load staticfiles %}


<!-- page head title -->
{% block base_title %}Consommations | {{ block.super }}{% endblock %}


{% block body_skin_class %}{{ block.super }}{%  endblock %}
<!-- changez block-super en la couleur de votre app -->

<!--
----    LEFT SIDEBAR
---->

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="spamConso" only %}
{% endblock %}


<!-- here add you own stylesheet and scripts in header -->
{% block base_header_addons %}
    <!-- Here : addons for the layout, in the whole App -->
    <link href="{% static 'spamConso/css/spamConso.css' %}" rel="stylesheet" type="text/css" />
    {% block page_header_addons %}
    {% endblock %}
{% endblock %}

<!-- here add you own stylesheet and scripts in footer-->
{% block base_footer_addons %}
    <!-- Here : addons for the layout, in the whole App-->

    <!-- ChartJS-->
    <script src="{% static 'LTE/plugins/chartjs/Chart.min.js' %}"></script>

    {% block page_footer_addons %}
    {% endblock %}
{% endblock %}

<!--
----    PAGE CONTENT HEADER
---->
<!-- Page content header title -->
{% block base_content_header_title %}Consommations | {{ block.super }}{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with current='SpamConso' only %}
{% endblock %}
<!--
----    RIGHT SIDEBAR
---->

<!--
----    PAGE CONTENT BODY
---->
<!-- Page content - body -->
{% block body %}{% endblock %}

spamConso/templates/spamConso/tacos.html
{% extends "spamConso/layout.html" %}
{% load staticfiles %}

<!-- page head title -->
{% block base_title %}Mon Tacos | {{ block.super }}{% endblock %}

<!-- Page content header title -->
{% block base_content_header_title %}#Tacos{% endblock %}

<!-- Page content header optional description -->
{% block base_content_header_title_description %}Ici tu peux avoir des graphes concernant les tacos{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
<!-- le breadcrumb peut aller jusqu'a une profondeur de 4 (previous4) -->

{% block page_header_addons %}
    <!-- select2 -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

<!-- Page content breadcrumb (fil d'arianne) -->
{% block base_content_header_breadcrumb %}
    {% include 'LTE/breadcrumb.html' with prev1Url='spamConso:index' prev1Name="SpamConso" current="Tacos" only %}
{% endblock %}

<!-- Left Sidebar Menu -->
{% block base_left_sidebar_menu %}
    {% include "LTE/menu.html" with active="spamConso/tacos" only %}
{% endblock %}

{% block page_footer_addons %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    <script>
        var mois = ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre'];
        var chartData = {
            labels: [{% for value in graphe %} "{{ value.xaxis }}" ,{% endfor %}],
            datasets: [
                {
                    label: "Biere per month dataset",
                    fillColor: "rgba(220,220,220,0.5)",
                    strokeColor: "rgba(220,220,220,0.8)",
                    highlightFill: "rgba(220,220,220,0.75)",
                    highlightStroke: "rgba(220,220,220,1)",
                    data: [{% for value in graphe %} {{ value.yaxis }}, {% endfor %}]
                }
            ]
        };

        $(function () {
            var ctx = document.getElementById("myChart").getContext("2d");
            var myChart = new Chart(ctx).Bar(chartData, {
                responsive: true,
                maintainAspectRatio: false
            });

            $('select').select2({
                width: '100%'
            });
        });
    </script>
{% endblock %}

{% block body %}
    <h3>Nombre de <b>Tacos</b> #{{ yaxis }} par {{ xaxis }}</h3>
    <form action="{% url 'spamConso:conso_view' %}?type=tacos" method="get" class="row">
        <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-0">
        <input name="type" value="tacos" hidden>
            <select name="yaxis">
                <option value="all">Tous</option>
                {% for conso_tag in conso_tags %}
                    <option value="{{ conso_tag.value }}"
                            {% ifequal conso_tag.value request.GET.yaxis %}selected="selected"{% endifequal %}>{{ conso_tag.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-0">
            <select name="xaxis">
                <option value="personne" {% ifequal "personne" request.GET.xaxis %}selected="selected"{% endifequal %}>
                    Par personne
                </option>
                <option value="date" {% ifequal "date" request.GET.xaxis %}selected="selected"{% endifequal %}>Par
                    mois
                </option>
            </select>
        </div>
        <div class="col-xs-4 col-xs-offset-4 col-md-4 col-md-offset-0">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Get !</button>
        </div>
    </form>
    <div class="row">
        <canvas id='myChart' class="col-xs-12" width="100%" height="400"></canvas>
    </div>

{% endblock %}